In [1]:
import pandas as pd
from geopy.geocoders import Nominatim
import tqdm
geolocator = Nominatim(user_agent="blah")

def fun(row):
    return row['Zone'] if '/' not in row['Zone'] else row['Zone'].split('/')[0]
    
df = pd.read_csv("taxi+_zone_lookup.csv")
df = df[df['Borough'] != 'Unknown']
df['loc'] = df.apply(fun, axis=1)

df['lat'] = 0
df['lng'] = 0

def get_lat_long(row):
    if row['lat'] !=0:
        return row
    location = None
    for suffix in [', New York', '', f", {row['Borough']}", ', New Jersey']:
        try:
            location = geolocator.geocode(row['loc'] + suffix)
            if location is not None and not (38 < location.latitude < 47 and -80 < location.longitude < -71):
                location = None
        except:
            pass
        if location is not None:
            break
        
    if location is not None:
        row['lat'] = location.latitude
        row['lng'] = location.longitude
    else:
        row['lat'] = 0.0
        row['lng'] = 0.0
    return row

for i, row in tqdm.tqdm(df.iterrows()):
    df.iloc[i] = get_lat_long(row)
df

263it [03:44,  1.17it/s]

,LocationID,Borough,Zone,service_zone,loc,lat,lng
0,1,EWR,Newark Airport,EWR,Newark Airport,0.000000,0.000000
1,2,Queens,Jamaica Bay,Boro Zone,Jamaica Bay,40.603994,-73.835412
2,3,Bronx,Allerton/Pelham Gardens,Boro Zone,Allerton,40.865430,-73.867365
3,4,Manhattan,Alphabet City,Yellow Zone,Alphabet City,40.725102,-73.979583
4,5,Staten Island,Arden Heights,Boro Zone,Arden Heights,40.557441,-74.188581
...,...,...,...,...,...,...,...
258,259,Bronx,Woodlawn/Wakefield,Boro Zone,Woodlawn,40.895753,-73.862452
259,260,Queens,Woodside,Boro Zone,Woodside,40.745380,-73.905415
260,261,Manhattan,World Trade Center,Yellow Zone,World Trade Center,40.711888,-74.012441
261,262,Manhattan,Yorkville East,Yellow Zone,Yorkville East,40.784505,-73.957003
262,263,Manhattan,Yorkville West,Yellow Zone,Yorkville West,40.810703,-73.404922

In [33]:
df.to_csv('taxi_zone_updated.csv', index=False)

In [26]:
[[60, 40.6681032, -73.94479939999997], [61, 40.6681032, -73.94479939999997], [86, 40.707491, -74.011276], [140, 40.766232, -73.960231], [178, 40.7643574, -73.9234619],
[217, 40.671592, -73.779798], [217, 40.671592, -73.779798], [237, 40.787011, -73.975368], [254, 40.71625, -73.958535], [255, 40.71625, -73.958535]]

[[60, 40.6681032, -73.94479939999997],
 [61, 40.6681032, -73.94479939999997],
 [86, 40.707491, -74.011276],
 [140, 40.766232, -73.960231],
 [178, 40.7643574, -73.9234619],
 [217, 40.671592, -73.779798],
 [217, 40.671592, -73.779798],
 [237, 40.787011, -73.975368],
 [254, 40.71625, -73.958535],
 [255, 40.71625, -73.958535]]

In [ ]:
'distanceto.com'